---
name: Security tests

on:
  push:
    branches:
      - main
      - 'bugfix/**'
      - 'feature/**'

jobs:
  security_tests:
    name: Security tests
    timeout-minutes: 10
    runs-on: ubuntu-latest
    container: snyk/snyk-cli:docker
    steps:
      - uses: actions/checkout@v2.3.4
        with:
          ref: ${{ github.ref }}
      - name: Test Dockerfile
        run: |
          docker build -t ${{ github.repository }}:${{ github.sha }} .
          snyk auth ${{ secrets.SNYK_API_TOKEN }}
          snyk test --docker ${{ github.repository }}:${{ github.sha }} --file=Dockerfile
